/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  title: 'Xeno',
  tagline: 'The production-ready TypeScript accelerator',
  favicon: 'img/favicon.ico',
  future: {
    v4: {
      removeLegacyPostBuildHeadAttribute: true,
      useCssCascadeLayers: true,
      siteStorageNamespacing: true,
      fasterByDefault: true,
      mdx1CompatDisabledByDefault: true,
    },
    experimental_vcs: {},
    experimental_router: 'browser',
    faster: {
      swcJsLoader: true,
      swcJsMinimizer: true,
      swcHtmlMinimizer: true,
      lightningCssMinimizer: true,
      mdxCrossCompilerCache: true,
      rspackBundler: true,
      rspackPersistentCache: true,
      ssgWorkerThreads: true,
      gitEagerVcs: true,
    },
  },
  url: 'https://Xeno.github.io',
  baseUrl: '/',
  organizationName: 'mattia-carcione',
  projectName: 'Xeno',
  onBrokenLinks: 'throw',
  i18n: {
    defaultLocale: 'en',
    locales: ['en'],
    path: 'i18n',
    localeConfigs: {},
  },
  presets: [
    [
      'classic',
      {
        docs: {
          path: '../documentation',
          routeBasePath: 'docs',
          sidebarPath: 'C:\\Users\\Mattia\\Desktop\\development\\gear5\\website\\sidebars.ts',
          editUrl: 'https://github.com/Mattia-Carcione/xeno-js/tree/main/',
        },
        blog: false,
        theme: {
          customCss:
            'C:\\Users\\Mattia\\Desktop\\development\\gear5\\website\\src\\css\\custom.css',
        },
      },
    ],
  ],
  themeConfig: {
    image: 'img/logo.png',
    colorMode: {
      respectPrefersColorScheme: true,
      defaultMode: 'light',
      disableSwitch: false,
    },
    navbar: {
      logo: {
        alt: 'Xeno Logo',
        src: 'img/logo.png',
        className: 'header-logo',
      },
      items: [
        {
          type: 'docSidebar',
          sidebarId: 'tutorialSidebar',
          position: 'left',
          label: 'Docs',
        },
        {
          'href': 'https://github.com/Mattia-Carcione/xeno-js',
          'className': 'header-github-link',
          'aria-label': 'GitHub repository',
          'position': 'right',
        },
      ],
      hideOnScroll: false,
    },
    footer: {
      style: 'dark',
      links: [],
      copyright:
        '\n      <div style="display: flex; justify-content: center; align-items: center; gap: 1rem; margin-bottom: 1rem;">\n        <a href="https://github.com/Mattia-Carcione/xeno-js" target="_blank" rel="noreferrer" aria-label="GitHub">\n          <img src="/img/github.svg" alt="GitHub" width="24" height="24" style="filter: brightness(0) invert(1);" />\n        </a>\n      </div>\n      Copyright © 2025 - 2026 By <a href="https://github.com/Mattia-Carcione">Mattia Carcione</a>.\n      ',
    },
    prism: {
      theme: {
        plain: {
          color: '#393A34',
          backgroundColor: '#f6f8fa',
        },
        styles: [
          {
            types: ['comment', 'prolog', 'doctype', 'cdata'],
            style: {
              color: '#999988',
              fontStyle: 'italic',
            },
          },
          {
            types: ['namespace'],
            style: {
              opacity: 0.7,
            },
          },
          {
            types: ['string', 'attr-value'],
            style: {
              color: '#e3116c',
            },
          },
          {
            types: ['punctuation', 'operator'],
            style: {
              color: '#393A34',
            },
          },
          {
            types: [
              'entity',
              'url',
              'symbol',
              'number',
              'boolean',
              'variable',
              'constant',
              'property',
              'regex',
              'inserted',
            ],
            style: {
              color: '#36acaa',
            },
          },
          {
            types: ['atrule', 'keyword', 'attr-name', 'selector'],
            style: {
              color: '#00a4db',
            },
          },
          {
            types: ['function', 'deleted', 'tag'],
            style: {
              color: '#d73a49',
            },
          },
          {
            types: ['function-variable'],
            style: {
              color: '#6f42c1',
            },
          },
          {
            types: ['tag', 'selector', 'keyword'],
            style: {
              color: '#00009f',
            },
          },
        ],
      },
      darkTheme: {
        plain: {
          color: '#F8F8F2',
          backgroundColor: '#282A36',
        },
        styles: [
          {
            types: ['prolog', 'constant', 'builtin'],
            style: {
              color: 'rgb(189, 147, 249)',
            },
          },
          {
            types: ['inserted', 'function'],
            style: {
              color: 'rgb(80, 250, 123)',
            },
          },
          {
            types: ['deleted'],
            style: {
              color: 'rgb(255, 85, 85)',
            },
          },
          {
            types: ['changed'],
            style: {
              color: 'rgb(255, 184, 108)',
            },
          },
          {
            types: ['punctuation', 'symbol'],
            style: {
              color: 'rgb(248, 248, 242)',
            },
          },
          {
            types: ['string', 'char', 'tag', 'selector'],
            style: {
              color: 'rgb(255, 121, 198)',
            },
          },
          {
            types: ['keyword', 'variable'],
            style: {
              color: 'rgb(189, 147, 249)',
              fontStyle: 'italic',
            },
          },
          {
            types: ['comment'],
            style: {
              color: 'rgb(98, 114, 164)',
            },
          },
          {
            types: ['attr-name'],
            style: {
              color: 'rgb(241, 250, 140)',
            },
          },
        ],
      },
      additionalLanguages: [],
      magicComments: [
        {
          className: 'theme-code-block-highlighted-line',
          line: 'highlight-next-line',
          block: {
            start: 'highlight-start',
            end: 'highlight-end',
          },
        },
      ],
    },
    docs: {
      versionPersistence: 'localStorage',
      sidebar: {
        hideable: false,
        autoCollapseCategories: false,
      },
    },
    blog: {
      sidebar: {
        groupByYear: true,
      },
    },
    metadata: [],
    tableOfContents: {
      minHeadingLevel: 2,
      maxHeadingLevel: 3,
    },
  },
  baseUrlIssueBanner: true,
  storage: {
    type: 'localStorage',
    namespace: true,
  },
  onBrokenAnchors: 'warn',
  onDuplicateRoutes: 'warn',
  staticDirectories: ['static'],
  customFields: {},
  plugins: [],
  themes: [],
  scripts: [],
  headTags: [],
  stylesheets: [],
  clientModules: [],
  titleDelimiter: '|',
  noIndex: false,
  markdown: {
    format: 'mdx',
    mermaid: false,
    emoji: true,
    mdx1Compat: {
      comments: false,
      admonitions: false,
      headingIds: false,
    },
    anchors: {
      maintainCase: false,
    },
    hooks: {
      onBrokenMarkdownLinks: 'warn',
      onBrokenMarkdownImages: 'throw',
    },
  },
}
